### ISSUE TITLE
(test) 팝업 정렬 이슈

### ISSUE THREAD

**Issue by netrue2021** [netrue2021/mirae_asset#3]
팝업 가운데 정렬 확인 부탁드립니다.
고정 fix 말고 가운데 정렬 되게 해주세요.

**Comment by netrue2021** [comment]
@dhhan8974 팀장님 

해당 이슈 확인부탁드립니다.
감사합니다.

**Comment by nyounghee02** [comment]
@dhhan8974 오오~ 예이~
